# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7e01bdb2bfdf266d9f16b82cf8a94723860df85207c47ab48fd209294c4ca708ad86dd9b2cdb1e4147bd610d19e72b29b85a867d767ad8bf12d80d143c4b723b

test:
  secret_key_base: 67689556b5fb80303e67125ed4a7e0fc47ce70a88067efef5c63f1a09480730adbd6a9c2440caa7767408bfa8c700a78ca9331420a221bfbe0cce5be3fb2ab0e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
